#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE                     0
#define ITEM_MASTER_BALL              1
#define ITEM_ULTRA_BALL               2
#define ITEM_GREAT_BALL               3
#define ITEM_POKE_BALL                4
#define ITEM_SAFARI_BALL              5
#define ITEM_NET_BALL                 6
#define ITEM_DIVE_BALL                7
#define ITEM_NEST_BALL                8
#define ITEM_REPEAT_BALL              9
#define ITEM_TIMER_BALL               10
#define ITEM_LUXURY_BALL              11
#define ITEM_PREMIER_BALL             12
// New Balls                     
#define ITEM_PARK_BALL                13
#define ITEM_CHERISH_BALL             14
#define ITEM_DUSK_BALL                15
#define ITEM_HEAL_BALL                16
#define ITEM_QUICK_BALL               17
#define ITEM_FAST_BALL                18
#define ITEM_LEVEL_BALL               19
#define ITEM_LURE_BALL                20
#define ITEM_HEAVY_BALL               21
#define ITEM_LOVE_BALL                22
#define ITEM_FRIEND_BALL              23
#define ITEM_MOON_BALL                24
#define ITEM_SPORT_BALL               25
#define ITEM_BEAST_BALL               26
#define ITEM_DREAM_BALL               27
// Medicine                      
#define ITEM_POTION                   28
#define ITEM_ANTIDOTE                 29
#define ITEM_BURN_HEAL                30
#define ITEM_ICE_HEAL                 31
#define ITEM_AWAKENING                32
#define ITEM_PARALYZE_HEAL            33
#define ITEM_FULL_RESTORE             34
#define ITEM_MAX_POTION               35
#define ITEM_HYPER_POTION             36
#define ITEM_SUPER_POTION             37
#define ITEM_FULL_HEAL                38
#define ITEM_REVIVE                   39
#define ITEM_MAX_REVIVE               40
#define ITEM_FRESH_WATER              41
#define ITEM_SODA_POP                 42
#define ITEM_LEMONADE                 43
#define ITEM_MOOMOO_MILK              44
#define ITEM_ENERGY_POWDER            45
#define ITEM_ENERGY_ROOT              46
#define ITEM_HEAL_POWDER              47
#define ITEM_REVIVAL_HERB             48
#define ITEM_ETHER                    49
#define ITEM_MAX_ETHER                50
#define ITEM_ELIXIR                   51
#define ITEM_MAX_ELIXIR               52
#define ITEM_LAVA_COOKIE              53
#define ITEM_BLUE_FLUTE               54
#define ITEM_YELLOW_FLUTE             55
#define ITEM_RED_FLUTE                56
#define ITEM_BLACK_FLUTE              57
#define ITEM_WHITE_FLUTE              58
#define ITEM_BERRY_JUICE              59
#define ITEM_SACRED_ASH               60
#define ITEM_SHOAL_SALT               61
#define ITEM_SHOAL_SHELL              62
#define ITEM_RED_SHARD                63
#define ITEM_BLUE_SHARD               64
#define ITEM_YELLOW_SHARD             65
#define ITEM_GREEN_SHARD              66
#define ITEM_HP_UP                    67
#define ITEM_PROTEIN                  68
#define ITEM_IRON                     69
#define ITEM_CARBOS                   70
#define ITEM_CALCIUM                  71
#define ITEM_RARE_CANDY               72
#define ITEM_PP_UP                    73
#define ITEM_ZINC                     74
#define ITEM_PP_MAX                   75
#define ITEM_GUARD_SPEC               76
#define ITEM_DIRE_HIT                 77
#define ITEM_X_ATTACK                 78
#define ITEM_X_DEFEND                 79
#define ITEM_X_SPEED                  80
#define ITEM_X_ACCURACY               81
#define ITEM_X_SPECIAL                82
#define ITEM_X_SPECIAL_DEFENSE        83
#define ITEM_POKE_DOLL                84
#define ITEM_FLUFFY_TAIL              85
#define ITEM_SUPER_REPEL              86
#define ITEM_MAX_REPEL                87
#define ITEM_ESCAPE_ROPE              88
#define ITEM_REPEL                    89
#define ITEM_SWEET_HEART              90
#define ITEM_BIG_MALASADA             91
#define ITEM_CASTELIACONE             92
#define ITEM_LUMIOSE_GALETTE          93
#define ITEM_RAGE_CANDY_BAR           94
#define ITEM_SHALOUR_SABLE            95
#define ITEM_OLD_GATEAU               96
// Evolution Items               
#define ITEM_SUN_STONE                97
#define ITEM_MOON_STONE               98
#define ITEM_FIRE_STONE               99
#define ITEM_THUNDER_STONE            100
#define ITEM_WATER_STONE              101
#define ITEM_LEAF_STONE               102
#define ITEM_DUSK_STONE               103
#define ITEM_DAWN_STONE               104
#define ITEM_SHINY_STONE              105
#define ITEM_OVAL_STONE               106
#define ITEM_ICE_STONE                107
#define ITEM_PROTECTOR                108
#define ITEM_MAGMARIZER               109
#define ITEM_PRISM_SCALE              110
#define ITEM_SACHET                   111
#define ITEM_WHIPPED_DREAM            112
#define ITEM_RAZOR_CLAW               113
#define ITEM_RAZOR_FANG               114
#define ITEM_REAPER_CLOTH             115
#define ITEM_DUBIOUS_DISC             116
#define ITEM_ELECTIRIZER              117
#define ITEM_LINK_STONE               118
#define ITEM_TART_APPLE               119
#define ITEM_SWEET_APPLE              120
#define ITEM_CRACKED_POT              121
#define ITEM_STRAWBERRY_SWEET         122
#define ITEM_BERRY_SWEET              123
#define ITEM_LOVE_SWEET               124
#define ITEM_CLOVER_SWEET             125
#define ITEM_FLOWER_SWEET             126
#define ITEM_RIBBON_SWEET             127
#define ITEM_STAR_SWEET               128
#define ITEM_CHIPPED_POT              129
#define ITEM_GALARICA_CUFF            130
#define ITEM_GALARICA_WREATH          131
// Wings                         
#define ITEM_HEALTH_WING              132
#define ITEM_MUSCLE_WING              133
#define ITEM_RESIST_WING              134
#define ITEM_GENIUS_WING              135
#define ITEM_CLEVER_WING              136
#define ITEM_SWIFT_WING               137
#define ITEM_PRETTY_WING              138
// Mints                         
#define ITEM_ADAMANT_MINT             139
#define ITEM_BOLD_MINT                140
#define ITEM_BRAVE_MINT               141
#define ITEM_CALM_MINT                142
#define ITEM_CAREFUL_MINT             143
#define ITEM_GENTLE_MINT              144
#define ITEM_HASTY_MINT               145
#define ITEM_IMPISH_MINT              146
#define ITEM_JOLLY_MINT               147
#define ITEM_LAX_MINT                 148
#define ITEM_LONELY_MINT              149
#define ITEM_MILD_MINT                150
#define ITEM_MODEST_MINT              151
#define ITEM_NAIVE_MINT               152
#define ITEM_NAUGHTY_MINT             153
#define ITEM_QUIET_MINT               154
#define ITEM_RASH_MINT                155
#define ITEM_RELAXED_MINT             156
#define ITEM_SASSY_MINT               157
#define ITEM_SERIOUS_MINT             158
#define ITEM_TIMID_MINT               159
// Valuable                      
#define ITEM_TINY_MUSHROOM            160
#define ITEM_BIG_MUSHROOM             161
#define ITEM_PEARL                    162
#define ITEM_BIG_PEARL                163
#define ITEM_STARDUST                 164
#define ITEM_STAR_PIECE               165
#define ITEM_NUGGET                   166
#define ITEM_HEART_SCALE              167
#define ITEM_RARE_BONE                168
#define ITEM_PEARL_STRING             169
#define ITEM_BIG_NUGGET               170
#define ITEM_COMET_SHARD              171
#define ITEM_BALM_MUSHROOM            172
// Mail                          
#define ITEM_ORANGE_MAIL              173
#define ITEM_HARBOR_MAIL              174
#define ITEM_GLITTER_MAIL             175
#define ITEM_MECH_MAIL                176
#define ITEM_WOOD_MAIL                177
#define ITEM_WAVE_MAIL                178
#define ITEM_BEAD_MAIL                179
#define ITEM_SHADOW_MAIL              180
#define ITEM_TROPIC_MAIL              181
#define ITEM_DREAM_MAIL               182
#define ITEM_FAB_MAIL                 183
#define ITEM_RETRO_MAIL               184
// Berries
#define ITEM_CHERI_BERRY              185
#define ITEM_CHESTO_BERRY             186
#define ITEM_PECHA_BERRY              187
#define ITEM_RAWST_BERRY              188
#define ITEM_ASPEAR_BERRY             189
#define ITEM_LEPPA_BERRY              190
#define ITEM_ORAN_BERRY               191
#define ITEM_PERSIM_BERRY             192
#define ITEM_LUM_BERRY                193
#define ITEM_SITRUS_BERRY             194
#define ITEM_FIGY_BERRY               195
#define ITEM_WIKI_BERRY               196
#define ITEM_MAGO_BERRY               197
#define ITEM_AGUAV_BERRY              198
#define ITEM_IAPAPA_BERRY             199
#define ITEM_RAZZ_BERRY               200
#define ITEM_BLUK_BERRY               201
#define ITEM_NANAB_BERRY              202
#define ITEM_WEPEAR_BERRY             203
#define ITEM_PINAP_BERRY              204
#define ITEM_POMEG_BERRY              205
#define ITEM_KELPSY_BERRY             206
#define ITEM_QUALOT_BERRY             207
#define ITEM_HONDEW_BERRY             208
#define ITEM_GREPA_BERRY              209
#define ITEM_TAMATO_BERRY             210
#define ITEM_CORNN_BERRY              211
#define ITEM_MAGOST_BERRY             212
#define ITEM_RABUTA_BERRY             213
#define ITEM_NOMEL_BERRY              214
#define ITEM_SPELON_BERRY             215
#define ITEM_PAMTRE_BERRY             216
#define ITEM_WATMEL_BERRY             217
#define ITEM_DURIN_BERRY              218
#define ITEM_BELUE_BERRY              219
#define ITEM_LIECHI_BERRY             220
#define ITEM_GANLON_BERRY             221
#define ITEM_SALAC_BERRY              222
#define ITEM_PETAYA_BERRY             223
#define ITEM_APICOT_BERRY             224
#define ITEM_LANSAT_BERRY             225
#define ITEM_STARF_BERRY              226
#define ITEM_OCCA_BERRY               227
#define ITEM_PASSHO_BERRY             228
#define ITEM_WACAN_BERRY              229
#define ITEM_RINDO_BERRY              230
#define ITEM_YACHE_BERRY              231
#define ITEM_CHOPLE_BERRY             232
#define ITEM_KEBIA_BERRY              233
#define ITEM_SHUCA_BERRY              234
#define ITEM_COBA_BERRY               235
#define ITEM_PAYAPA_BERRY             236
#define ITEM_TANGA_BERRY              237
#define ITEM_CHARTI_BERRY             238
#define ITEM_KASIB_BERRY              239
#define ITEM_HABAN_BERRY              240
#define ITEM_COLBUR_BERRY             241
#define ITEM_BABIRI_BERRY             242
#define ITEM_CHILAN_BERRY             243
#define ITEM_MICLE_BERRY              244
#define ITEM_CUSTAP_BERRY             245
#define ITEM_JABOCA_BERRY             246
#define ITEM_ROWAP_BERRY              247
#define ITEM_ROSELI_BERRY             248
#define ITEM_KEE_BERRY                249
#define ITEM_MARANGA_BERRY            250
#define ITEM_ENIGMA_BERRY             251
// Battle                        
#define ITEM_BRIGHT_POWDER            252
#define ITEM_WHITE_HERB               253
#define ITEM_MACHO_BRACE              254
#define ITEM_EXP_SHARE                255
#define ITEM_QUICK_CLAW               256
#define ITEM_SOOTHE_BELL              257
#define ITEM_MENTAL_HERB              258
#define ITEM_CHOICE_BAND              259
#define ITEM_KINGS_ROCK               260
#define ITEM_SILVER_POWDER            261
#define ITEM_AMULET_COIN              262
#define ITEM_CLEANSE_TAG              263
#define ITEM_SOUL_DEW                 264
#define ITEM_DEEP_SEA_TOOTH           265
#define ITEM_DEEP_SEA_SCALE           266
#define ITEM_SMOKE_BALL               267
#define ITEM_EVERSTONE                268
#define ITEM_FOCUS_BAND               269
#define ITEM_LUCKY_EGG                270
#define ITEM_SCOPE_LENS               271
#define ITEM_METAL_COAT               272
#define ITEM_LEFTOVERS                273
#define ITEM_DRAGON_SCALE             274
#define ITEM_LIGHT_BALL               275
#define ITEM_SOFT_SAND                276
#define ITEM_HARD_STONE               277
#define ITEM_MIRACLE_SEED             278
#define ITEM_BLACK_GLASSES            279
#define ITEM_BLACK_BELT               280
#define ITEM_MAGNET                   281
#define ITEM_MYSTIC_WATER             282
#define ITEM_SHARP_BEAK               283
#define ITEM_POISON_BARB              284
#define ITEM_NEVER_MELT_ICE           285
#define ITEM_SPELL_TAG                286
#define ITEM_TWISTED_SPOON            287
#define ITEM_CHARCOAL                 288
#define ITEM_DRAGON_FANG              289
#define ITEM_SILK_SCARF               290
#define ITEM_UP_GRADE                 291
#define ITEM_SHELL_BELL               292
#define ITEM_SEA_INCENSE              293
#define ITEM_LAX_INCENSE              294
#define ITEM_LUCKY_PUNCH              295
#define ITEM_METAL_POWDER             296
#define ITEM_THICK_CLUB               297
#define ITEM_LEEK                     298
#define ITEM_ADAMANT_ORB              299
#define ITEM_LUSTROUS_ORB             300
#define ITEM_GRISEOUS_ORB             301
#define ITEM_EXPERT_BELT              302
#define ITEM_POWER_HERB               303
#define ITEM_WIDE_LENS                304
#define ITEM_ZOOM_LENS                305
#define ITEM_DESTINY_KNOT             306
#define ITEM_SMOOTH_ROCK              307
#define ITEM_DAMP_ROCK                308
#define ITEM_HEAT_ROCK                309
#define ITEM_ICY_ROCK                 310
#define ITEM_BIG_ROOT                 311
#define ITEM_LIGHT_CLAY               312
#define ITEM_SAFETY_GOGGLES           313
#define ITEM_ROCKY_HELMET             314
#define ITEM_WEAKNESS_POLICY          315
#define ITEM_ASSAULT_VEST             316
#define ITEM_EVIOLITE                 317
#define ITEM_ABSORB_BULB              318
#define ITEM_AIR_BALLOON              319
#define ITEM_ADRENALINE_ORB           320
#define ITEM_BINDING_BAND             321
#define ITEM_CELL_BATTERY             322
#define ITEM_EJECT_BUTTON             323
#define ITEM_FLOAT_STONE              324
#define ITEM_FOCUS_SASH               325
#define ITEM_GRIP_CLAW                326
#define ITEM_IRON_BALL                327
#define ITEM_LAGGING_TAIL             328
#define ITEM_LUMINOUS_MOSS            329
#define ITEM_QUICK_POWDER             330
#define ITEM_METRONOME                331
#define ITEM_MUSCLE_BAND              332
#define ITEM_PROTECTIVE_PADS          333
#define ITEM_RED_CARD                 334
#define ITEM_RING_TARGET              335
#define ITEM_SHED_SHELL               336
#define ITEM_SNOWBALL                 337
#define ITEM_STICKY_BARB              338
#define ITEM_TERRAIN_EXTENDER         339
#define ITEM_WISE_GLASSES             340
#define ITEM_ELECTRIC_SEED            341
#define ITEM_GRASSY_SEED              342
#define ITEM_MISTY_SEED               343
#define ITEM_PSYCHIC_SEED             344
#define ITEM_LIFE_ORB                 345
#define ITEM_TOXIC_ORB                346
#define ITEM_FLAME_ORB                347
#define ITEM_BLACK_SLUDGE             348
#define ITEM_CHOICE_SPECS             349
#define ITEM_CHOICE_SCARF             350
#define ITEM_EJECT_PACK               351
#define ITEM_ROOM_SERVICE             352
#define ITEM_BLUNDER_POLICY           353
#define ITEM_HEAVY_DUTY_BOOTS         354
#define ITEM_UTILITY_UMBRELLA         355
#define ITEM_THROAT_SPRAY             356
// Power Items                   
#define ITEM_POWER_BRACER             357
#define ITEM_POWER_BELT               358
#define ITEM_POWER_LENS               359
#define ITEM_POWER_BAND               360
#define ITEM_POWER_ANKLET             361
#define ITEM_POWER_WEIGHT             362
// Incenses                      
#define ITEM_LUCK_INCENSE             363
#define ITEM_FULL_INCENSE             364
#define ITEM_ODD_INCENSE              365
#define ITEM_PURE_INCENSE             366
#define ITEM_ROCK_INCENSE             367
#define ITEM_ROSE_INCENSE             368
#define ITEM_WAVE_INCENSE             369
// Apricorns                     
#define ITEM_RED_APRICORN             370
#define ITEM_BLUE_APRICORN            371
#define ITEM_YELLOW_APRICORN          372
#define ITEM_GREEN_APRICORN           373
#define ITEM_PINK_APRICORN            374
#define ITEM_WHITE_APRICORN           375
#define ITEM_BLACK_APRICORN           376
// Mega                          
#define ITEM_ULTRANECROZIUM_Z         377
#define ITEM_VENUSAURITE              378
#define ITEM_CHARIZARDITE_X           379
#define ITEM_CHARIZARDITE_Y           380
#define ITEM_BLASTOISINITE            381
#define ITEM_BEEDRILLITE              382
#define ITEM_PIDGEOTITE               383
#define ITEM_ALAKAZITE                384
#define ITEM_SLOWBRONITE              385
#define ITEM_GENGARITE                386
#define ITEM_KANGASKHANITE            387
#define ITEM_PINSIRITE                388
#define ITEM_GYARADOSITE              389
#define ITEM_AERODACTYLITE            390
#define ITEM_MEWTWONITE_X             391
#define ITEM_MEWTWONITE_Y             392
#define ITEM_AMPHAROSITE              393
#define ITEM_STEELIXITE               394
#define ITEM_SCIZORITE                395
#define ITEM_HERACRONITE              396
#define ITEM_HOUNDOOMINITE            397
#define ITEM_TYRANITARITE             398
#define ITEM_SCEPTILITE               399
#define ITEM_BLAZIKENITE              400
#define ITEM_SWAMPERTITE              401
#define ITEM_GARDEVOIRITE             402
#define ITEM_SABLENITE                403
#define ITEM_MAWILITE                 404
#define ITEM_AGGRONITE                405
#define ITEM_MEDICHAMITE              406
#define ITEM_MANECTITE                407
#define ITEM_SHARPEDONITE             408
#define ITEM_CAMERUPTITE              409
#define ITEM_ALTARIANITE              410
#define ITEM_BANETTITE                411
#define ITEM_ABSOLITE                 412
#define ITEM_GLALITITE                413
#define ITEM_SALAMENCITE              414
#define ITEM_METAGROSSITE             415
#define ITEM_LATIASITE                416
#define ITEM_LATIOSITE                417
#define ITEM_LOPUNNITE                418
#define ITEM_GARCHOMPITE              419
#define ITEM_LUCARIONITE              420
#define ITEM_ABOMASITE                421
#define ITEM_GALLADITE                422
#define ITEM_AUDINITE                 423
#define ITEM_DIANCITE                 424
// Gems                          
#define ITEM_NORMAL_GEM               425
#define ITEM_FIGHTING_GEM             426
#define ITEM_FLYING_GEM               427
#define ITEM_POISON_GEM               428
#define ITEM_GROUND_GEM               429
#define ITEM_ROCK_GEM                 430
#define ITEM_BUG_GEM                  431
#define ITEM_GHOST_GEM                432
#define ITEM_STEEL_GEM                433
#define ITEM_FIRE_GEM                 434
#define ITEM_WATER_GEM                435
#define ITEM_GRASS_GEM                436
#define ITEM_ELECTRIC_GEM             437
#define ITEM_PSYCHIC_GEM              438
#define ITEM_ICE_GEM                  439
#define ITEM_DRAGON_GEM               440
#define ITEM_DARK_GEM                 441
#define ITEM_FAIRY_GEM                442
// Plates                        
#define ITEM_FIST_PLATE               443
#define ITEM_SKY_PLATE                444
#define ITEM_TOXIC_PLATE              445
#define ITEM_EARTH_PLATE              446
#define ITEM_STONE_PLATE              447
#define ITEM_INSECT_PLATE             448
#define ITEM_SPOOKY_PLATE             449
#define ITEM_IRON_PLATE               450
#define ITEM_FLAME_PLATE              451
#define ITEM_SPLASH_PLATE             452
#define ITEM_MEADOW_PLATE             453
#define ITEM_ZAP_PLATE                454
#define ITEM_MIND_PLATE               455
#define ITEM_ICICLE_PLATE             456
#define ITEM_DRACO_PLATE              457
#define ITEM_DREAD_PLATE              458
#define ITEM_PIXIE_PLATE              459
// Drives                        
#define ITEM_BURN_DRIVE               460
#define ITEM_DOUSE_DRIVE              461
#define ITEM_SHOCK_DRIVE              462
#define ITEM_CHILL_DRIVE              463
// Memories                      
#define ITEM_FIGHTING_MEMORY          464
#define ITEM_FLYING_MEMORY            465
#define ITEM_POISON_MEMORY            466
#define ITEM_GROUND_MEMORY            467
#define ITEM_ROCK_MEMORY              468
#define ITEM_BUG_MEMORY               469
#define ITEM_GHOST_MEMORY             470
#define ITEM_STEEL_MEMORY             471
#define ITEM_FIRE_MEMORY              472
#define ITEM_WATER_MEMORY             473
#define ITEM_GRASS_MEMORY             474
#define ITEM_ELECTRIC_MEMORY          475
#define ITEM_PSYCHIC_MEMORY           476
#define ITEM_ICE_MEMORY               477
#define ITEM_DRAGON_MEMORY            478
#define ITEM_DARK_MEMORY              479
#define ITEM_FAIRY_MEMORY             480
// Z Crystals                    
#define ITEM_NORMALIUM_Z              481
#define ITEM_FIGHTINIUM_Z             482
#define ITEM_FLYINIUM_Z               483
#define ITEM_POISONIUM_Z              484
#define ITEM_GROUNDIUM_Z              485
#define ITEM_ROCKIUM_Z                486
#define ITEM_BUGINIUM_Z               487
#define ITEM_GHOSTIUM_Z               488
#define ITEM_STEELIUM_Z               489
#define ITEM_FIRIUM_Z                 490
#define ITEM_WATERIUM_Z               491
#define ITEM_GRASSIUM_Z               492
#define ITEM_ELECTRIUM_Z              493
#define ITEM_PSYCHIUM_Z               494
#define ITEM_ICIUM_Z                  495
#define ITEM_DRAGONIUM_Z              496
#define ITEM_DARKINIUM_Z              497
#define ITEM_FAIRIUM_Z                498
#define ITEM_ALORAICHIUM_Z            499
#define ITEM_DECIDIUM_Z               500
#define ITEM_EEVIUM_Z                 501
#define ITEM_INCINIUM_Z               502
#define ITEM_KOMMONIUM_Z              503
#define ITEM_LUNALIUM_Z               504
#define ITEM_LYCANIUM_Z               505
#define ITEM_MARSHADIUM_Z             506
#define ITEM_MEWNIUM_Z                507
#define ITEM_MIMIKIUM_Z               508
#define ITEM_PIKANIUM_Z               509
#define ITEM_PIKASHUNIUM_Z            510
#define ITEM_PRIMARIUM_Z              511
#define ITEM_SNORLIUM_Z               512
#define ITEM_SOLGANIUM_Z              513
#define ITEM_TAPUNIUM_Z               514
// New Fossils                   
#define ITEM_SKULL_FOSSIL             515
#define ITEM_ARMOR_FOSSIL             516
#define ITEM_COVER_FOSSIL             517
#define ITEM_PLUME_FOSSIL             518
#define ITEM_JAW_FOSSIL               519
#define ITEM_SAIL_FOSSIL              520
// Random                        
#define ITEM_ABILITY_CAPSULE          521
#define ITEM_ODD_KEYSTONE             522
#define ITEM_BOTTLE_CAP               523
#define ITEM_GOLD_BOTTLE_CAP          524
#define ITEM_WISHING_PIECE            525
#define ITEM_HONEY                    526
// Nectars                       
#define ITEM_RED_NECTAR               527
#define ITEM_YELLOW_NECTAR            528
#define ITEM_PINK_NECTAR              529
#define ITEM_PURPLE_NECTAR            530
// Relics                        
#define ITEM_RELIC_COPPER             531
#define ITEM_RELIC_SILVER             532
#define ITEM_RELIC_GOLD               533
#define ITEM_RELIC_VASE               534
#define ITEM_RELIC_BAND               535
#define ITEM_RELIC_STATUE             536
#define ITEM_RELIC_CROWN              537
// New Key Items                 
#define ITEM_OVAL_CHARM               538
#define ITEM_SHINY_CHARM              539
#define ITEM_RAINBOW_WING             540
#define ITEM_SILVER_WING              541
#define ITEM_MAGMA_STONE              542
#define ITEM_N_SOLARIZER              543
#define ITEM_N_LUNARIZER              544
#define ITEM_SUN_FLUTE                545
#define ITEM_MOON_FLUTE               546
#define ITEM_LIGHT_STONE              547
#define ITEM_DARK_STONE               548
#define ITEM_GRACIDEA                 549
#define ITEM_DNA_SPLICERS             550
#define ITEM_REVEAL_GLASS             551
#define ITEM_PRISON_BOTTLE            552
#define ITEM_MEGA_BRACELET            553
#define ITEM_Z_RING                   554
#define ITEM_DYNAMAX_BAND             555
// Key                           
#define ITEM_RED_SCARF                556
#define ITEM_BLUE_SCARF               557
#define ITEM_PINK_SCARF               558
#define ITEM_GREEN_SCARF              559
#define ITEM_YELLOW_SCARF             560
#define ITEM_MACH_BIKE                561
#define ITEM_COIN_CASE                562
#define ITEM_ITEMFINDER               563
#define ITEM_OLD_ROD                  564
#define ITEM_GOOD_ROD                 565
#define ITEM_SUPER_ROD                566
#define ITEM_SS_TICKET                567
#define ITEM_CONTEST_PASS             568
#define ITEM_WAILMER_PAIL             569
#define ITEM_DEVON_GOODS              570
#define ITEM_SOOT_SACK                571
#define ITEM_BASEMENT_KEY             572
#define ITEM_ACRO_BIKE                573
#define ITEM_POKEBLOCK_CASE           574
#define ITEM_LETTER                   575
#define ITEM_EON_TICKET               576
#define ITEM_RED_ORB                  577
#define ITEM_BLUE_ORB                 578
#define ITEM_SCANNER                  579
#define ITEM_GO_GOGGLES               580
#define ITEM_METEORITE                581
#define ITEM_ROOM_1_KEY               582
#define ITEM_ROOM_2_KEY               583
#define ITEM_ROOM_4_KEY               584
#define ITEM_ROOM_6_KEY               585
#define ITEM_STORAGE_KEY              586
#define ITEM_ROOT_FOSSIL              587
#define ITEM_CLAW_FOSSIL              588
#define ITEM_DEVON_SCOPE              589
// TmHm                          
#define ITEM_TM01                     590
#define ITEM_TM02                     591
#define ITEM_TM03                     592
#define ITEM_TM04                     593
#define ITEM_TM05                     594
#define ITEM_TM06                     595
#define ITEM_TM07                     596
#define ITEM_TM08                     597
#define ITEM_TM09                     598
#define ITEM_TM10                     599
#define ITEM_TM11                     600
#define ITEM_TM12                     601
#define ITEM_TM13                     602
#define ITEM_TM14                     603
#define ITEM_TM15                     604
#define ITEM_TM16                     605
#define ITEM_TM17                     606
#define ITEM_TM18                     607
#define ITEM_TM19                     608
#define ITEM_TM20                     609
#define ITEM_TM21                     610
#define ITEM_TM22                     611
#define ITEM_TM23                     612
#define ITEM_TM24                     613
#define ITEM_TM25                     614
#define ITEM_TM26                     615
#define ITEM_TM27                     616
#define ITEM_TM28                     617
#define ITEM_TM29                     618
#define ITEM_TM30                     619
#define ITEM_TM31                     620
#define ITEM_TM32                     621
#define ITEM_TM33                     622
#define ITEM_TM34                     623
#define ITEM_TM35                     624
#define ITEM_TM36                     625
#define ITEM_TM37                     626
#define ITEM_TM38                     627
#define ITEM_TM39                     628
#define ITEM_TM40                     629
#define ITEM_TM41                     630
#define ITEM_TM42                     631
#define ITEM_TM43                     632
#define ITEM_TM44                     633
#define ITEM_TM45                     634
#define ITEM_TM46                     635
#define ITEM_TM47                     636
#define ITEM_TM48                     637
#define ITEM_TM49                     638
#define ITEM_TM50                     639
#define ITEM_TM51                     640
#define ITEM_TM52                     641
#define ITEM_TM53                     642
#define ITEM_TM54                     643
#define ITEM_TM55                     644
#define ITEM_TM56                     645
#define ITEM_TM57                     646
#define ITEM_TM58                     647
#define ITEM_TM59                     648
#define ITEM_TM60                     649
#define ITEM_TM61                     650
#define ITEM_TM62                     651
#define ITEM_TM63                     652
#define ITEM_TM64                     653
#define ITEM_TM65                     654
#define ITEM_TM66                     655
#define ITEM_TM67                     656
#define ITEM_TM68                     657
#define ITEM_TM69                     658
#define ITEM_TM70                     659
#define ITEM_TM71                     660
#define ITEM_TM72                     661
#define ITEM_TM73                     662
#define ITEM_TM74                     663
#define ITEM_TM75                     664
#define ITEM_TM76                     665
#define ITEM_TM77                     666
#define ITEM_TM78                     667
#define ITEM_TM79                     668
#define ITEM_TM80                     669
#define ITEM_TM81                     670
#define ITEM_TM82                     671
#define ITEM_TM83                     672
#define ITEM_TM84                     673
#define ITEM_TM85                     674
#define ITEM_TM86                     675
#define ITEM_TM87                     676
#define ITEM_TM88                     677
#define ITEM_TM89                     678
#define ITEM_TM90                     679
#define ITEM_TM91                     680
#define ITEM_TM92                     681
#define ITEM_TM93                     682
#define ITEM_TM94                     683
#define ITEM_TM95                     684
#define ITEM_TM96                     685
#define ITEM_TM97                     686
#define ITEM_TM98                     687
#define ITEM_TM99                     688
#define ITEM_TM100                    689
#define ITEM_HM01                     690
#define ITEM_HM02                     691
#define ITEM_HM03                     692
#define ITEM_HM04                     693
#define ITEM_HM05                     694
#define ITEM_HM06                     695
#define ITEM_HM07                     696
#define ITEM_HM08                     697

#define ITEM_FIRST_TM           ITEM_TM01
#define ITEM_LAST_TM            ITEM_TM100
#define ITEM_TMHM_END           ITEM_HM08
#define NUM_TECHNICAL_MACHINES  100
#define NUM_HIDDEN_MACHINES     8
#define NUM_TMHMS               NUM_TECHNICAL_MACHINES + NUM_HIDDEN_MACHINES
#define REUSABLE_TMS        //comment this line out to have tms be consumable

// FireRed/LeafGreen
#define ITEM_OAKS_PARCEL    ITEM_TMHM_END + 1
#define ITEM_POKE_FLUTE     ITEM_TMHM_END + 2
#define ITEM_SECRET_KEY     ITEM_TMHM_END + 3
#define ITEM_BIKE_VOUCHER   ITEM_TMHM_END + 4
#define ITEM_GOLD_TEETH     ITEM_TMHM_END + 5
#define ITEM_OLD_AMBER      ITEM_TMHM_END + 6
#define ITEM_CARD_KEY       ITEM_TMHM_END + 7
#define ITEM_LIFT_KEY       ITEM_TMHM_END + 8
#define ITEM_HELIX_FOSSIL   ITEM_TMHM_END + 9
#define ITEM_DOME_FOSSIL    ITEM_TMHM_END + 10
#define ITEM_SILPH_SCOPE    ITEM_TMHM_END + 11
#define ITEM_BICYCLE        ITEM_TMHM_END + 12
#define ITEM_TOWN_MAP       ITEM_TMHM_END + 13
#define ITEM_VS_SEEKER      ITEM_TMHM_END + 14
#define ITEM_FAME_CHECKER   ITEM_TMHM_END + 15
#define ITEM_TM_CASE        ITEM_TMHM_END + 16
#define ITEM_BERRY_POUCH    ITEM_TMHM_END + 17
#define ITEM_TEACHY_TV      ITEM_TMHM_END + 18
#define ITEM_TRI_PASS       ITEM_TMHM_END + 19
#define ITEM_RAINBOW_PASS   ITEM_TMHM_END + 20
#define ITEM_TEA            ITEM_TMHM_END + 21
#define ITEM_MYSTIC_TICKET  ITEM_TMHM_END + 22
#define ITEM_AURORA_TICKET  ITEM_TMHM_END + 23
#define ITEM_POWDER_JAR     ITEM_TMHM_END + 24    
#define ITEM_RUBY           ITEM_TMHM_END + 25
#define ITEM_SAPPHIRE       ITEM_TMHM_END + 26

#define ITEM_N_A            ITEM_TMHM_END + 27

// Emerald
#define ITEM_MAGMA_EMBLEM   ITEM_TMHM_END + 28
#define ITEM_OLD_SEA_MAP    ITEM_TMHM_END + 29


#define ITEM_TM01_WORK_UP           ITEM_TM01
#define ITEM_TM02_DRAGON_CLAW       ITEM_TM02
#define ITEM_TM03_PSYSHOCK          ITEM_TM03
#define ITEM_TM04_CALM_MIND         ITEM_TM04
#define ITEM_TM05_ROAR              ITEM_TM05
#define ITEM_TM06_TOXIC             ITEM_TM06
#define ITEM_TM07_HAIL              ITEM_TM07
#define ITEM_TM08_BULK_UP           ITEM_TM08
#define ITEM_TM09_VENOSHOCK         ITEM_TM09
#define ITEM_TM10_HIDDEN_POWER      ITEM_TM10
#define ITEM_TM11_SUNNY_DAY         ITEM_TM11
#define ITEM_TM12_TAUNT             ITEM_TM12
#define ITEM_TM13_ICE_BEAM          ITEM_TM13
#define ITEM_TM14_BLIZZARD          ITEM_TM14
#define ITEM_TM15_HYPER_BEAM        ITEM_TM15
#define ITEM_TM16_LIGHT_SCREEN      ITEM_TM16
#define ITEM_TM17_PROTECT           ITEM_TM17
#define ITEM_TM18_RAIN_DANCE        ITEM_TM18
#define ITEM_TM19_ROOST             ITEM_TM19
#define ITEM_TM20_SAFEGUARD         ITEM_TM20
#define ITEM_TM21_FRUSTRATION       ITEM_TM21
#define ITEM_TM22_SOLAR_BEAM        ITEM_TM22
#define ITEM_TM23_SMACK_DOWN        ITEM_TM23
#define ITEM_TM24_THUNDERBOLT       ITEM_TM24
#define ITEM_TM25_THUNDER           ITEM_TM25
#define ITEM_TM26_EARTHQUAKE        ITEM_TM26
#define ITEM_TM27_RETURN            ITEM_TM27
#define ITEM_TM28_LEECH_LIFE        ITEM_TM28
#define ITEM_TM29_PSYCHIC           ITEM_TM29
#define ITEM_TM30_SHADOW_BALL       ITEM_TM30
#define ITEM_TM31_BRICK_BREAK       ITEM_TM31
#define ITEM_TM32_DOUBLE_TEAM       ITEM_TM32
#define ITEM_TM33_REFLECT           ITEM_TM33
#define ITEM_TM34_SLUDGE_WAVE       ITEM_TM34
#define ITEM_TM35_FLAMETHROWER      ITEM_TM35
#define ITEM_TM36_SLUDGE_BOMB       ITEM_TM36
#define ITEM_TM37_SANDSTORM         ITEM_TM37
#define ITEM_TM38_FIRE_BLAST        ITEM_TM38
#define ITEM_TM39_ROCK_TOMB         ITEM_TM39
#define ITEM_TM40_AERIAL_ACE        ITEM_TM40
#define ITEM_TM41_TORMENT           ITEM_TM41
#define ITEM_TM42_FACADE            ITEM_TM42
#define ITEM_TM43_FLAME_CHARGE      ITEM_TM43
#define ITEM_TM44_REST              ITEM_TM44
#define ITEM_TM45_ATTRACT           ITEM_TM45
#define ITEM_TM46_THIEF             ITEM_TM46
#define ITEM_TM47_LOW_SWEEP         ITEM_TM47
#define ITEM_TM48_ROUND             ITEM_TM48
#define ITEM_TM49_ECHOED_VOICE      ITEM_TM49
#define ITEM_TM50_OVERHEAT          ITEM_TM50
#define ITEM_TM51_STEEL_WING        ITEM_TM51
#define ITEM_TM52_FOCUS_BLAST       ITEM_TM52
#define ITEM_TM53_ENERGY_BALL       ITEM_TM53
#define ITEM_TM54_FALSE_SWIPE       ITEM_TM54
#define ITEM_TM55_SCALD             ITEM_TM55
#define ITEM_TM56_FLING             ITEM_TM56
#define ITEM_TM57_CHARGE_BEAM       ITEM_TM57
#define ITEM_TM58_SKY_DROP          ITEM_TM58
#define ITEM_TM59_BRUTAL_SWING      ITEM_TM59
#define ITEM_TM60_QUASH             ITEM_TM60
#define ITEM_TM61_WILL_O_WISP       ITEM_TM61
#define ITEM_TM62_ACROBATICS        ITEM_TM62
#define ITEM_TM63_EMBARGO           ITEM_TM63
#define ITEM_TM64_EXPLOSION         ITEM_TM64
#define ITEM_TM65_SHADOW_CLAW       ITEM_TM65
#define ITEM_TM66_PAYBACK           ITEM_TM66
#define ITEM_TM67_SMART_STRIKE      ITEM_TM67
#define ITEM_TM68_GIGA_IMPACT       ITEM_TM68
#define ITEM_TM69_ROCK_POLISH       ITEM_TM69
#define ITEM_TM70_AURORA_VEIL       ITEM_TM70
#define ITEM_TM71_STONE_EDGE        ITEM_TM71
#define ITEM_TM72_VOLT_SWITCH       ITEM_TM72
#define ITEM_TM73_THUNDER_WAVE      ITEM_TM73
#define ITEM_TM74_GYRO_BALL         ITEM_TM74
#define ITEM_TM75_SWORDS_DANCE      ITEM_TM75
#define ITEM_TM76_FLY               ITEM_TM76
#define ITEM_TM77_PSYCH_UP          ITEM_TM77
#define ITEM_TM78_BULLDOZE          ITEM_TM78
#define ITEM_TM79_FROST_BREATH      ITEM_TM79
#define ITEM_TM80_ROCK_SLIDE        ITEM_TM80
#define ITEM_TM81_X_SCISSOR         ITEM_TM81
#define ITEM_TM82_DRAGON_TAIL       ITEM_TM82
#define ITEM_TM83_INFESTATION       ITEM_TM83
#define ITEM_TM84_POISON_JAB        ITEM_TM84
#define ITEM_TM85_DREAM_EATER       ITEM_TM85
#define ITEM_TM86_GRASS_KNOT        ITEM_TM86
#define ITEM_TM87_SWAGGER           ITEM_TM87
#define ITEM_TM88_SLEEP_TALK        ITEM_TM88
#define ITEM_TM89_U_TURN            ITEM_TM89
#define ITEM_TM90_SUBSTITUTE        ITEM_TM90
#define ITEM_TM91_FLASH_CANNON      ITEM_TM91
#define ITEM_TM92_TRICK_ROOM        ITEM_TM92
#define ITEM_TM93_WILD_CHARGE       ITEM_TM93
#define ITEM_TM94_SURF              ITEM_TM94
#define ITEM_TM95_SNARL             ITEM_TM95
#define ITEM_TM96_NATURE_POWER      ITEM_TM96
#define ITEM_TM97_DARK_PULSE        ITEM_TM97
#define ITEM_TM98_WATERFALL         ITEM_TM98
#define ITEM_TM99_DAZZLING_GLEAM    ITEM_TM99
#define ITEM_TM100_CONFIDE          ITEM_TM100
#define ITEM_HM01_CUT               ITEM_HM01
#define ITEM_HM02_FLY               ITEM_HM02
#define ITEM_HM03_SURF              ITEM_HM03
#define ITEM_HM04_STRENGTH          ITEM_HM04
#define ITEM_HM05_FLASH             ITEM_HM05
#define ITEM_HM06_ROCK_SMASH        ITEM_HM06
#define ITEM_HM07_WATERFALL         ITEM_HM07
#define ITEM_HM08_DIVE              ITEM_HM08

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX ITEM_ENIGMA_BERRY
#define ITEM_TO_BERRY(itemId)(((itemId - FIRST_BERRY_INDEX) + 1))

// Check if the item is one that can be used on a Pokemon.
#define IS_POKEMON_ITEM(item) ((item) >= ITEM_POTION && (item) <= ITEM_ENIGMA_BERRY)

#endif  // GUARD_CONSTANTS_ITEMS_H
